require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.telescope'
require 'user.lsp'
require 'user.cmp'
require 'user.lualine'
require 'user.autopairs'
require 'user.treesitter'
require 'user.scroll'
require 'user.nvim-tree'
require 'user.comment'
require 'user.fidget'

vim.cmd 'source ~/.config/nvim/core/floatterm.vim'
